export { Dashboard } from './Dashboard'
export { Contatos } from './Contatos'
export { ContatoDetalhe } from './ContatoDetalhe'
export { NovaVenda } from './NovaVenda'
export { Vendas } from './Vendas'
export { VendaDetalhe } from './VendaDetalhe'
export { Indicacoes } from './Indicacoes'
export { Recompra } from './Recompra'
export { Configuracoes } from './Configuracoes'

